=== osoclos/cultivis/src/data/schemas/characters/player-data.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "player-data.schema.json",

    "title": "Player Data",
    "description": "Information on players that provides creature and fleece metadata.",

    "type": "object",
    "properties": {
        "creatures": {
            "type": "object",
            "propertyNames": { "$ref": "#/definitions/CreatureId" },
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The display name of this creature."
                    },

                    "variant": {
                        "type": "string",
                        "description": "The variant name of this creature."
                    }
                },

                "required": ["name", "variant"]
            }
        },

        "crowns": {
            "type": "object",
            "propertyNames": { "$ref": "#/definitions/CrownId" },
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The display name of this crown."
                    },

                    "variant": {
                        "type": "string",
                        "description": "The variant name of this crown."
                    }
                },

                "required": ["name", "variant"]
            }
        },

        "fleeces": {
            "type": "object",
            "propertyNames": { "$ref": "#/definitions/FleeceId" },
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The display name of this fleece."
                    },

                    "category": {
                        "type": "integer",
                        "description": "The category index in the crown menu which this fleece belongs to.",

                        "minimum": 0,
                        "maximum": 2
                    },

                    "variant": {
                        "type": "string",
                        "description": "The variant name of this fleece."
                    }
                },

                "required": ["name", "category", "variant"]
            }
        },

        "bells": {
            "type": "object",
            "propertyNames": { "$ref": "#/definitions/BellId" },
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The display name of this bell."
                    },

                    "category": {
                        "type": "integer",
                        "description": "The category index in the crown menu which this bell belongs to.",

                        "minimum": 0,
                        "maximum": 2
                    },

                    "variant": {
                        "type": "string",
                        "description": "The variant name of this bell."
                    }
                },

                "required": ["name", "category", "variant"]
            }
        }
    },

    "required": ["creatures", "crowns", "fleeces", "bells"],
    "definitions": {
        "CreatureId": {
            "type": "string",
            "enum": ["Lamb", "Goat"]
        },

        "CrownId": {
            "type": "string",
            "enum": ["Red", "Purple"]
        },

        "FleeceId": {
            "type": "string",
            "enum": ["Lamb", "Goat", "Golden", "Glass", "Diseased", "Fates", "Fragile", "Cursed", "Berserker", "Fervor", "Hobbled", "Heretic", "Natural", "Silk", "God", "Cowboy", "Rags"]
        },

        "BellId": {
            "type": "string",
            "enum": ["Lamb", "Goat", "Golden", "Glass", "Diseased", "Fates", "Fragile", "Cursed", "Berserker", "Fervor", "Hobbled", "God", "Cowboy"]
        }
    }
}

=== osoclos/cultivis/src/data/files/characters/player-data.json
{
    "creatures": {
        "Lamb": {
            "name": "Lamb",
            "variant": "Lamb"
        },
        
        "Goat": {
            "name": "Goat",
            "variant": "Goat"
        }
    },

    "crowns": {
        "Red": {
            "name": "Red Crown",
            "variant": "Lamb"
        },

        "Purple": {
            "name": "Purple Crown",
            "variant": "Goat"
        }
    },

    "fleeces": {
        "Lamb": {
            "name": "Fleece of the Lamb",
            "category": 0,

            "variant": "Lamb_0"
        },

        "Goat": {
            "name": "Fleece of the Goat",
            "category": 0,

            "variant": "Goat"
        },

        "Golden": {
            "name": "Golden Fleece",
            "category": 0,

            "variant": "Lamb_1"
        },

        "Glass": {
            "name": "Fleece of the Glass Cannon",
            "category": 0,

            "variant": "Lamb_2"
        },

        "Diseased": {
            "name": "Fleece of the Diseased Heart",
            "category": 0,

            "variant": "Lamb_3"
        },

        "Fates": {
            "name": "Fleece of the Fates",
            "category": 0,

            "variant": "Lamb_4"
        },

        "Fragile": {
            "name": "Fleece of Fragile Fortitude",
            "category": 0,

            "variant": "Lamb_5"
        },

        "Cursed": {
            "name": "Fleece of a Cursed Crusade",
            "category": 1,

            "variant": "Lamb_6"
        },

        "Berserker": {
            "name": "Fleece of the Berserker",
            "category": 1,

            "variant": "Lamb_7"
        },

        "Fervor": {
            "name": "Fleece of Fervor's Favor",
            "category": 1,

            "variant": "Lamb_8"
        },

        "Hobbled": {
            "name": "Fleece of the Hobbled Heels",
            "category": 1,

            "variant": "Lamb_9"
        },

        "Heretic": {
            "name": "Fleece of the Heretics",
            "category": 2,

            "variant": "Lamb_999"
        },

        "Natural": {
            "name": "Fleece of the Natural",
            "category": 2,

            "variant": "Lamb_1001"
        },

        "Silk": {
            "name": "Silk Fleece",
            "category": 2,

            "variant": "Lamb_1002"
        },

        "God": {
            "name": "God of Death Fleece",
            "category": 2,

            "variant": "Lamb_1000"
        },

        "Cowboy": {
            "name": "Cowboy",
            "category": 2,

            "variant": "Lamb_676"
        },

        "Rags": {
            "name": "Rags",
            "category": 0,

            "variant": "Lamb_Intro"
        }
    },

    "bells": {
        "Lamb": {
            "name": "Bell of the Lamb",
            "category": 0,

            "variant": "Lamb_0"
        },

        "Goat": {
            "name": "Bell of the Goat",
            "category": 0,

            "variant": "Goat"
        },

        "Golden": {
            "name": "Golden Bell",
            "category": 0,

            "variant": "Lamb_1"
        },

        "Glass": {
            "name": "Glass Bell",
            "category": 0,

            "variant": "Lamb_2"
        },

        "Diseased": {
            "name": "Diseased Bell",
            "category": 0,

            "variant": "Lamb_3"
        },

        "Fates": {
            "name": "Fateful Bell",
            "category": 0,

            "variant": "Lamb_4"
        },

        "Fragile": {
            "name": "Fragile Bell",
            "category": 0,

            "variant": "Lamb_5"
        },

        "Cursed": {
            "name": "Cursed Bell",
            "category": 1,

            "variant": "Lamb_6"
        },

        "Berserker": {
            "name": "Bell of the Berserker",
            "category": 1,

            "variant": "Lamb_7"
        },

        "Fervor": {
            "name": "Bell of Fervor's Favor",
            "category": 1,

            "variant": "Lamb_8"
        },

        "Hobbled": {
            "name": "Bell of the Hobbled Heels",
            "category": 1,

            "variant": "Lamb_9"
        },

        "God": {
            "name": "God of Death Necklace",
            "category": 2,

            "variant": "Lamb_1000"
        },

        "Cowboy": {
            "name": "Sheriff Badge",
            "category": 2,

            "variant": "Lamb_676"
        }
    }
}
